[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  # Environment variables must be set in Netlify dashboard
  # Go to: Site settings > Environment variables
  # Add these variables:
  # VITE_SUPABASE_URL = "https://your-project-id.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"